### ISSUE TITLE
tests error

### ISSUE THREAD

**Issue by tigercosmos** [BlackGlory/async-proxy#1]
node  v14

```log
tigercosmos@tigercosmos-sslab:~/async-proxy$ npm test

> async-proxy@0.4.0 test /home/tigercosmos/async-proxy
> node --harmony ./node_modules/jest/bin/jest.js --coverage --config jest.config.json

 FAIL  test/example.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  test/async-proxy.test.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "branches" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "lines" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.753s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by BlackGlory** [comment]
The error cannot be reproduced on my platform, please provide the following information:
1. Are you using yarn to install dependencies?
2. Your node.js version, yarn version

**Comment by tigercosmos** [comment]
No, I use node 14's npm. I thought npm do the same as yarn, so is it only for yarn?

**Comment by BlackGlory** [comment]
They are different, npm uses [package-lock.json](https://docs.npmjs.com/configuring-npm/package-lock-json.html), yarn uses [yarn.lock](https://classic.yarnpkg.com/en/docs/yarn-lock/).
You need to install the dependencies with yarn.

**Comment by tigercosmos** [comment]
I don't think so. No matter yarn or npm both use `package.json`. The  `.lock` file is created from `package.json` and it makes sure the dependencies versions are fixed. IMO, it should work for npm too.

**Comment by BlackGlory** [comment]
Unfortunately, you are wrong.

If `package.json` was sufficient to handle the versions of all dependencies (and their dependencies), the "lock" solutions even would never have been invented.
